spring:
  application:
    name: naming-server
  security:
    user:
      name: app-blesk-naming-server
      password: b1477e9ba7723b8f47e9727a39a51edf
server:
  error:
    whitelabel:
      enabled: false
  port: 8761
eureka:
  password: b1477e9ba7723b8f47e9727a39a51edf
  client:
    serviceUrl:
      defaultZone: http://app-blesk-naming-server:b1477e9ba7723b8f47e9727a39a51edf@localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}