spring:
  application:
    name: naming-server
  security:
    user:
      name: app-blesk-naming-server
      password: b1477e9ba7723b8f47e9727a39a51edf
server:
  error:
    whitelabel:
      enabled: false
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  password: b1477e9ba7723b8f47e9727a39a51edf